### ISSUE TITLE
Ore Seasonal Shop description

### ISSUE THREAD

**Issue by HaiMisterGuy** [Arks-Layer/PSO2ENPatchCSV#1979]
![image](https://user-images.githubusercontent.com/120022329/211895977-f32ca77a-2c4f-4639-ab12-f33747e0c8ef.png)
ui_mainmode - SeasonEvent_Reb_ItemExchange_2lineguide#0

**Comment by DabirSA** [comment]
Resolved in c28673b2f852a2f6266132055e92ea46b8e25402
