### ISSUE TITLE
No free space for fashion item error message

### ISSUE THREAD

**Issue by HaiMisterGuy** [Arks-Layer/PSO2ENPatchCSV#2016]
![image](https://user-images.githubusercontent.com/120022329/219959331-39984c0a-04c7-417a-9efa-a104890d985f.png)
EN
ui_esthetic_text - Result_14#0
OR
ui_fashion_manager_text - MyFashion_ServerError20#0

**Comment by DabirSA** [comment]
Fixed by 0a2f80beba9c95b48edebf3eb7bcff56d3f698c1
