### ISSUE TITLE
NGS Notice Message

### ISSUE THREAD

**Issue by HaiMisterGuy** [Arks-Layer/PSO2ENPatchCSV#2080]
![image](https://github.com/Arks-Layer/PSO2ENPatchCSV/assets/120022329/555cdebb-9481-4303-b17a-842fd2c15f0b)
EN - ui_title_text - EP1_3_CloseIntroduction#0

**Comment by DabirSA** [comment]
Resolved by b91a235f1c5bfed130c140bf995079da0e1947bc
