### ISSUE TITLE
Pet Ability Level Clipping

### ISSUE THREAD

**Issue by reveriadive** [Arks-Layer/PSO2ENPatchCSV#305]
Can "Enjoys Sun" be changed to "Basking"? (It's the best I can think of that'll fit.)
It cuts off important information with the Super prefix.
![info](https://user-images.githubusercontent.com/17341158/30622471-73b4d554-9d77-11e7-9a74-3542db5a00cd.png)
(Well I guess this isn't that big of a deal since it's view-able in tab 3.)

**Comment by SynthSy** [comment]
We're not changing it.

**Comment by chaoko99** [comment]
Might I ask why?

**Comment by SynthSy** [comment]
If it wasn't view-able in both tabs, then it would be subject to change.
