### ISSUE TITLE
All Tech PP save's effects are written wrong.

### ISSUE THREAD

**Issue by chaoko99** [Arks-Layer/PSO2ENPatchCSV#308]
![lblnzi0](https://user-images.githubusercontent.com/4706052/30710289-f19fbbda-9eb9-11e7-9330-7bf279433b24.png)

PP consumption rate is wrong here, it should be PP cost reduction or something to that effect.

It doesn't make resta cost 2 pp.

**Comment by alama** [comment]
Noting where the strings are in question:

[ui_mainmode.csv `AllTechPPSave#0`](https://github.com/Arks-Layer/PSO2ENPatchCSV/blob/EN/UI/ui_mainmode.csv#L1955)
JP: `オールテック<br>ＰＰセイブ`
EN: `All Tech <br>PP Save`

[ui_mainmode.csv `AllTechPPSave#1`](https://github.com/Arks-Layer/PSO2ENPatchCSV/blob/EN/UI/ui_mainmode.csv#L2372)
JP: `全てのテクニックの消費ＰＰが減少する`
EN: `Reduces the PP consumption of all Techniques.`

[ui_mainmode.csv `PpTecRate#0`](https://github.com/Arks-Layer/PSO2ENPatchCSV/blob/EN/UI/ui_mainmode.csv#L2587)
JP: `ＰＰ消費割合`
EN: `PP Consumption Rate`

**Comment by chaoko99** [comment]
Resolved?

**Comment by SynthSy** [comment]
We don't see a problem here. 
`消費` means consumption; to spend
`割合` means rate; ratio; percentage; proportion​.

**Comment by SynthSy** [comment]
Also, don't know where your math is at, but resta uses 30 PP, what this skill does is reduce that number. 20% of 30 is not 2.

**Comment by chaoko99** [comment]
You're nitpicking. My point is that written as is, it is misleading.

**Comment by SynthSy** [comment]
> You're nitpicking. My point is that written as is, it is misleading.

How so?

**Comment by chaoko99** [comment]
My math is off. So what? My point stands in that it is a % reduction, not a % multiplication.

Consumption rate implies that your PP cost becomes [cost] * 8%, or 8% of the cost. 
It's actually lowered by eight percent.

**Comment by chaoko99** [comment]
Also:
![image](https://user-images.githubusercontent.com/4706052/30768042-6ec75d7c-9fb7-11e7-8776-f272c49c1cb8.png)

PSO2 rounds up, so it'd be 3.

**Comment by Aida-Enna** [comment]
It fits what SEGA wrote, and if we wanted to sit here and fix all of SEGA's mistakes, we'd just end up with Final Fantasy XIV or Guild Wars 2. It's their dumb phrasing, and unless a large number of people are confused as to the meaning, we're going to go with what they put.

Also, 2 is not 3.

**Comment by Kyle873** [comment]
Just to amend something here real quick. PSO2 does not always round up. it almost always truncates.
