### ISSUE TITLE
Yellow text in Stratos's partner card item is cut off.

### ISSUE THREAD

**Issue by chaoko99** [Arks-Layer/PSO2ENPatchCSV#362]
![Yellow text in Stratos's partner card item is cut off.](https://i.imgur.com/JABtI6l.png)

**Comment by alama** [comment]
[Treasure_145#1](https://github.com/Arks-Layer/PSO2ENPatchCSV/blob/EN/UI/ui_mainmode.csv#L3916)

**Comment by SynthSy** [comment]
Closing this because it's either been fixed already, or something we cannot fix without editing the game's code.
