### ISSUE TITLE
How can I build and install the language patch?

### ISSUE THREAD

**Issue by kirchner-trevor** [Arks-Layer/PSO2ENPatchCSV#658]
Hi,

I am interested in contributing to the project, but I would like to try building and applying my translations to my copy of the game before I submit a pull request. Is this possible?

**Comment by Aida-Enna** [comment]
Unfortunately not. Sorry! But we'll be able to address any incorrect spacing issues or other glaring things once it's brought into the patch itself and we're able to see it ingame (which is also, unfortunately, what we have to do on patch night before the servers come back up, for example.)

**Comment by Aida-Enna** [comment]
(Gonna close this, but feel free to comment on it later if you have any further questions/comments!)
